version: '3.8'

services:
  Frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
  Backend:
    build: ./Backend
    ports:
      - "3000:3000"
      - "3001:3001"
    deploy:
      resources:
        limits:
          memory: 8G
    env_file:
      - .env
    restart: always